# Generated by Django 5.1.4 on 2025-01-05 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voyages", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
        migrations.RemoveField(
            model_name="avis",
            name="lieu",
        ),
        migrations.AddField(
            model_name="avis",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avis",
                to="voyages.destination",
            ),
        ),
    ]
