# Generated by Django 5.1.4 on 2025-01-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voyages", "0004_avis_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="destination_images/"
            ),
        ),
    ]
